name: test_diliana
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.181009940803051
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
