name: test_diliana
favicon: null
layout_spectrum: 0.3166684773750603
typography_spectrum: 0.48919747676700354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.181009940803051
  lightness: 0.5449388320557773
  saturation: 0.6867208522744477
  rhythmicContrast: 0.34060141164809465
purpose: []
